name: deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: production
      url: http://example.com

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ secrets.FOO_TOKEN }}
