name: deploy

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: production
      url: http://example.com

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2

    - name: Diff files in db/migrate
      id: migrate
      run: |
        MIGRATE_SIZE=$(git diff --name-only @^ -- db/migrate | wc -l)
        echo "::set-output name=size::$MIGRATE_SIZE"

    - name: Display diff_files
      run: echo ${{ steps.migrate.outputs.size }}

    - name: Run db:migrate
      if: steps.migrate.outputs.size != '0'
      run: echo "bin/rails db:migrate"

    - name: Display SHA
      run: echo "${{ github.event.pull_request.head.sha }}"
