name: label test

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  run:
    if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: test
      run: |
        echo ${{ github.event_path }}
        cat ${{ github.event_path }} | jq
