name: matrix test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      name: ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        name: [foo, bar]

    steps:
    - name: sleep
      run: |
        SLEEP_TIME=$(( $RANDOM % 10 ))
        echo $SLEEP_TIME
        sleep $SLEEP_TIME

  after:
    needs: run
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - run: |
        echo "${{ needs.run.outputs.name }} OK"
