name: rollback

on: workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: production
      url: http://example.com

    steps:
    - name: Disallow rollback on branches other than main
      if: github.event.ref != 'refs/heads/main'
      run: exit 1

    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 2

    - name: Find revision to deploy
      id: revision
      run: |
        PREV_REV=$(git rev-parse @^@ | tail -1)
        echo "::set-output name=sha::$PREV_REV"

    - name: Diff files in db/migrate
      id: migrate
      run: |
        MIGRATE_SIZE=$(git diff --name-only @^ -- db/migrate | wc -l)
        echo "::set-output name=size::$MIGRATE_SIZE"

    - name: Display diff_files
      run: echo ${{ steps.migrate.outputs.size }}

    - name: Run db:rollback
      if: steps.migrate.outputs.size != '0'
      run: echo "bin/rails db:rollback STEP=${{ steps.migrate.outputs.size }}"

    - name: Display SHA
      run: echo "${{ steps.revision.outputs.sha }}"
